In [1]:
import pandas as pd
import numpy as np
import gurobipy as gp
from gurobipy import GRB

import datetime as dt
import plotly.graph_objects as go

from tqdm import tqdm

In [2]:
data = pd.read_parquet("stock_data.parquet")
stock_names = data['comnam'].unique()

# repeat = True
# while repeat:
#     count = 0
#     dfs = []
#     sizes = []
#     relevant_stocks = np.random.choice(stock_names,size=10, replace=False)
#     for stock in relevant_stocks:
#         subset = data[data['comnam'] == stock]
#         df = subset[['prc']]
#         df.columns = [stock]
#         df.index = pd.to_datetime(subset['date'])
#         dfs.append(df)
#         sizes.append(df.shape[0])
#     dfs = [x for _,x in reversed(sorted(zip(sizes,dfs), key = lambda x:x[0]))]
#     final = dfs[0]
#     for i in range(1, 10):
#         final = final.join(dfs[i])
#     final.index.name = 'date'
#     final = final.groupby(by='date').mean()
#     final = final.interpolate()
#     period = np.random.randint(30, final.shape[0])
#     final = final.iloc[period-30:period]
#     if final.iloc[0].isna().any() or final.iloc[29].isna().any():
#         repeat = True
#     else:
#         repeat = False

In [3]:
data

cusip   permno   permco   issuno  hexcd  hsiccd       date  \
33229   68389X10  10104.0   8045.0  10536.0    1.0  7372.0 2020-01-02   
33230   68389X10  10104.0   8045.0  10536.0    1.0  7372.0 2020-01-03   
33231   68389X10  10104.0   8045.0  10536.0    1.0  7372.0 2020-01-06   
33232   68389X10  10104.0   8045.0  10536.0    1.0  7372.0 2020-01-07   
33233   68389X10  10104.0   8045.0  10536.0    1.0  7372.0 2020-01-08   
...          ...      ...      ...      ...    ...     ...        ...   
340541  88160R10  93436.0  53453.0  66252.0    3.0  9999.0 2022-03-25   
340542  88160R10  93436.0  53453.0  66252.0    3.0  9999.0 2022-03-28   
340543  88160R10  93436.0  53453.0  66252.0    3.0  9999.0 2022-03-29   
340544  88160R10  93436.0  53453.0  66252.0    3.0  9999.0 2022-03-30   
340545  88160R10  93436.0  53453.0  66252.0    3.0  9999.0 2022-03-31   

              bidlo        askhi          prc  ...          bid          ask  \
33229     53.230000    53.959999    53.950001  ...    53.950001    53.959999   
33230     52.950001    54.049999    53.759998  ...    53.770000    53.779999   
33231     53.349998    54.200001    54.040001  ...    54.040001    54.049999   
33232     53.610001    54.330002    54.160000  ...    54.160000    54.169998   
33233     53.700001    54.599998    54.130001  ...    54.119999    54.130001   
...             ...          ...          ...  ...          ...          ...   
340541   997.320129  1021.799927  1010.640015  ...  1010.210022  1010.890015   
340542  1053.599976  1097.879883  1091.839966  ...  1091.839966  1092.199951   
340543  1073.109985  1114.770020  1099.569946  ...  1099.819946  1099.959961   
340544  1084.000000  1113.949951  1093.989990  ...  1093.689941  1093.989990   
340545  1076.640991  1103.139893  1077.599976  ...  1077.599976  1077.880005   

           shrout  cfacpr  cfacshr      openprc     numtrd      retx  ticker  \
33229   3207649.0     1.0      1.0    53.270000        NaN  0.018309    ORCL   
33230   3207649.0     1.0      1.0    52.990002        NaN -0.003522    ORCL   
33231   3207649.0     1.0      1.0    53.360001        NaN  0.005208    ORCL   
33232   3207649.0     1.0      1.0    53.889999        NaN  0.002221    ORCL   
33233   3207649.0     1.0      1.0    53.939999        NaN -0.000554    ORCL   
...           ...     ...      ...          ...        ...       ...     ...   
340541  1033534.0     1.0      1.0  1008.000000   593068.0 -0.003235    TSLA   
340542  1033534.0     1.0      1.0  1065.099976  1113132.0  0.080345    TSLA   
340543  1033534.0     1.0      1.0  1107.989990   835619.0  0.007080    TSLA   
340544  1033534.0     1.0      1.0  1091.170044   598381.0 -0.005075    TSLA   
340545  1033534.0     1.0      1.0  1094.569946   509355.0 -0.014982    TSLA   

                     comnam  
33229   ORACLE SYSTEMS CORP  
33230   ORACLE SYSTEMS CORP  
33231   ORACLE SYSTEMS CORP  
33232   ORACLE SYSTEMS CORP  
33233   ORACLE SYSTEMS CORP  
...                     ...  
340541            TESLA INC  
340542            TESLA INC  
340543            TESLA INC  
340544            TESLA INC  
340545            TESLA INC  

[3441305 rows x 22 columns]

In [4]:
# Pivot data (columns: stock name, index: date)
data_pivot = data.pivot_table(index="date", values="prc", columns="comnam")

# Remove stocks with na in price column random stocks
# TODO: Remove the complete stock if any na
data_clean = data_pivot.dropna(axis=1, how='any')
data_clean
# # Pick 10 stocks at random
# relevant_stocks = np.random.choice(data_clean.columns,size=10, replace=False)
# data_filt = data_clean[relevant_stocks]

# # Focus on window of 30 trading days with random start dt
# start_dt = np.random.choice(data_filt.index[:-30],size=1, replace=False)[0]
# final = data_pivot.query("date >= @start_dt")
# final = final.iloc[:30]

# final
# data_filt

comnam      10X GENOMICS INC       3M CO  A C C O BRANDS CORP  A D T INC  \
date                                                                       
2020-01-02         72.830002  180.000000                 9.11       7.57   
2020-01-03         75.559998  178.449997                 8.99       7.45   
2020-01-06         75.550003  178.619995                 9.08       7.56   
2020-01-07         75.980003  177.899994                 8.87       7.44   
2020-01-08         74.839996  180.630005                 8.84       6.81   
...                      ...         ...                  ...        ...   
2022-03-25         67.790001  150.460007                 8.19       7.36   
2022-03-28         70.410004  149.470001                 8.19       7.45   
2022-03-29         77.250000  152.080002                 8.34       7.85   
2022-03-30         74.739998  151.429993                 8.17       7.59   
2022-03-31         76.070000  148.880005                 8.00       7.59   

comnam      A E S CORP  A H BELO CORP  A M B PROPERTY CORP  \
date                                                         
2020-01-02   20.030001          2.830            88.400002   
2020-01-03   19.799999          2.820            89.389999   
2020-01-06   20.030001          2.920            89.040001   
2020-01-07   20.100000          2.910            88.470001   
2020-01-08   20.059999          2.891            88.949997   
...                ...            ...                  ...   
2022-03-25   24.370001          6.940           157.330002   
2022-03-28   24.650000          7.030           160.350006   
2022-03-29   25.450001          6.970           164.699997   
2022-03-30   25.450001          6.980           164.139999   
2022-03-31   25.730000          7.000           161.479996   

comnam      A M N HEALTHCARE SERVICES INC  A M R CORP DEL  A P A CORP  ...  \
date                                                                   ...   
2020-01-02                      62.110001       29.090000   25.360001  ...   
2020-01-03                      62.419998       27.650000   25.690001  ...   
2020-01-06                      62.110001       27.320000   25.639999  ...   
2020-01-07                      62.049999       27.219999   32.509998  ...   
2020-01-08                      63.490002       27.840000   32.730000  ...   
...                                   ...             ...         ...  ...   
2022-03-25                     102.250000       17.010000   41.529999  ...   
2022-03-28                     105.510002       17.299999   39.849998  ...   
2022-03-29                     106.440002       18.160000   40.959999  ...   
2022-03-30                     105.750000       18.049999   41.200001  ...   
2022-03-31                     104.330002       18.250000   41.330002  ...   

comnam      ZAYRE CORP  ZEBRA TECHNOLOGIES CORP  ZILLOW GROUP INC  ZILLOW INC  \
date                                                                            
2020-01-02   61.700001               259.140015         45.157499   45.000000   
2020-01-03   61.240002               256.049988         44.680001   44.560001   
2020-01-06   61.630001               258.010010         44.587500   44.430000   
2020-01-07   61.590000               256.470001         45.697500   45.480000   
2020-01-08   61.919998               247.639999         45.672501   45.380001   
...                ...                      ...               ...         ...   
2022-03-25   61.290001               425.660004         51.742500   50.849998   
2022-03-28   62.000000               422.279999         52.474999   51.500000   
2022-03-29   64.309998               438.100006         55.107499   54.110001   
2022-03-30   62.000000               429.609985         52.185000   51.180000   
2022-03-31   60.580002               413.700012         49.025001   48.230000   

comnam      ZIMMER BIOMET HOLDINGS INC  ZIMMER HOLDINGS INC  \
date                                                          
2020-01-0

Create an initial portfolio

In [5]:
def get_prices_window(prices, start_dt):
    # Pick 10 stocks at random
    relevant_stocks = np.random.choice(prices.columns,size=10, replace=False)
    prices_filt = prices[relevant_stocks]

    final = prices_filt.query("date >= @start_dt")
    final = final.iloc[:30]
    return final

def generate_portfolios(stock_prices, init_budget=100000):
    initial_budget = init_budget
    initial_prices = stock_prices.iloc[0].to_numpy()
    # available_money = initial_budget * .95
    available_money = initial_budget
    P_0 = np.zeros(10) #initial portfolio
    break_bool = True
    ignore =  np.random.randint(0,10)
    while break_bool:
        stock_buy = np.random.randint(0,10)
        price = initial_prices[stock_buy]
        if stock_buy != ignore:
            if (available_money * .75) - price >= 0:
                available_money = available_money - price
                P_0[stock_buy] = P_0[stock_buy] + 1
            else:
                break_bool = False

    # w_0 = initial_budget * .05 + available_money
    w_0 = available_money
    # print(w_0)
    # print(P_0)
    final_prices = stock_prices.iloc[29].to_numpy()
    available_money = initial_budget * .9
    break_bool = True
    P_t = np.zeros(10) #target portfolio

    while break_bool:
        stock_buy = np.random.randint(0,10)
        price = final_prices[stock_buy]
        if available_money - price >= 0:
            available_money = available_money - price
            P_t[stock_buy] = P_t[stock_buy] + 1
        else:
            break_bool = False
    # print(P_t)
    return P_0, P_t, w_0, initial_prices, final_prices

# Formulations

## With Perfect Information

In [6]:
def get_naive_opt(P_0, P_t, w_0, initial_budget, initial_prices, final_prices, print_bool=False):
    F = 5.95 * np.ones(10)# trading fees
    # P_0 = starting portfolio
    # P_t = target portfolio
    # w_0 = starting cash
    # w_f = final free cash
    # budget = 20000
    M = initial_budget

    # Silence Gurobi output
    env = gp.Env(empty=True)
    env.setParam("OutputFlag",0)
    env.start()

    m = gp.Model(env=env)
    # Define Variables
    P_buy = m.addMVar((10,), vtype=GRB.INTEGER)
    P_sell = m.addMVar((10,), vtype=GRB.INTEGER)
    z_sell = m.addMVar((10,), vtype=GRB.BINARY)
    z_buy = m.addMVar((10,), vtype=GRB.BINARY)
    # Constraints

    ## Meet Target
    m.addConstr(
        P_0 + P_buy - P_sell >= P_t
    )

    ## Have Money
    m.addConstr(
        w_0 + initial_prices @ P_sell - initial_prices @ P_buy - F @ z_sell - F @ z_buy >=0
    )

    ## if we sell a stock, we pay a trading price
    m.addConstr(
        M*(z_sell) >= P_sell
    )

    ## If we buy a stock, we pay a trading fee

    m.addConstr(
        M*(z_buy) >= P_buy
    )

    cash = w_0 + initial_prices @ P_sell - initial_prices @ P_buy
    # Set objective: Maximize end portfolio value
    m.ModelSense = GRB.MAXIMIZE
    # try:
    m.setObjective(
        # cash - F @ z_sell - F @ z_buy + final_prices @ (P_0 + P_buy - P_sell)
        cash + final_prices @ (P_0 + P_buy - P_sell)
    )
    # except Exception as e:
        # print(e)
        # print((cash - F @ z_sell - F @ z_buy + final_prices @ (P_0 + P_buy - P_sell)).getValue())
        # print(cash.x)
        # print(z_sell.x)
        # print(z_buy.x)
        # print(final_prices)
        # print(P_0.x)
        # print(P_buy.x)
        # print(P_sell.x)

    m.optimize()
    final_portfolio = P_0 + P_buy.x - P_sell.x
    # free_cash = w_0 + initial_prices @ P_sell.x - initial_prices @ P_buy.x
    cash = cash.getValue()
    final_portfolio_value = cash + final_prices @ final_portfolio
    
    if print_bool:
        print(f"Init Portf Value: {initial_prices @ P_0}")
        print(f"Final Portfolio Value: {final_portfolio_value}")
        print(f"Cash Init: {w_0}")
        print(f"Cash Final: {cash}")
        print(f"Init Portfolio: {P_0}")
        print(f"Final Portfolio: {final_portfolio}")
        print(f"Target Portfolio: {P_t}")
        print(f"TX Vec Buy: {z_buy.x}")
        print(f"TX Vec Sell: {z_sell.x}")
        print(f"Total Tx Costs: {F @ z_sell.x + F @ z_buy.x}")
    return final_portfolio_value, final_portfolio, cash

In [7]:
# test
rng = np.random.default_rng()
budget = rng.integers(low=1000, high=10000, size=1)[0]
start_dt = np.random.choice(data_pivot.index[:-30], size=1, replace=True)[0]
stock_price_window = get_prices_window(data_clean, start_dt)
P_0, P_t, w_0, initial_prices, final_prices = generate_portfolios(stock_prices = stock_price_window, init_budget=budget)
final_portfolio_value, final_portfolio, free_cash = get_naive_opt(P_0, P_t, w_0, budget, initial_prices, final_prices, print_bool=True)

Init Portf Value: 3352.129997253418
Final Portfolio Value: 3746.1300048828125
Cash Init: 86.87000274658203
Cash Final: 61.799983978271484
Init Portfolio: [5. 3. 4. 3. 0. 4. 3. 3. 1. 0.]
Final Portfolio: [ 1.  1.  2.  3. 10.  2.  5.  4.  0.  2.]
Target Portfolio: [1. 1. 2. 3. 5. 0. 5. 4. 0. 2.]
TX Vec Buy: [0. 1. 0. 0. 1. 0. 1. 1. 0. 1.]
TX Vec Sell: [1. 1. 1. 0. 0. 1. 0. 0. 1. 0.]
Total Tx Costs: 59.5


## Multi-stage

##

In [8]:
def get_multi_stage_opt(P_0, P_t, w_0, initial_budget, stock_price_window, print_bool=False):   
    # Silence Gurobi output
    env = gp.Env(empty=True)
    env.setParam("OutputFlag",0)
    env.start()

    F = 5.95  * np.ones(10)# trading fees
    # prices = stock_price_window.interpolate().to_numpy()
    prices = stock_price_window.to_numpy()
    M = initial_budget
    # P_0 = starting portfolio
    # P_t = target portfolio
    # w_0 = starting cash

    m = gp.Model(env=env)

    # Define Variables
    P_buy = m.addMVar((30,10), vtype=GRB.INTEGER)
    P_sell = m.addMVar((30,10), vtype=GRB.INTEGER)
    z_sell = m.addMVar((30,10), vtype=GRB.BINARY)
    z_buy = m.addMVar((30,10), vtype=GRB.BINARY)
    P_time = m.addMVar((30,10), vtype=GRB.INTEGER)
    # P_time = np.ndarray((30,10))
    w = m.addMVar((30,), vtype=GRB.CONTINUOUS, lb = 0)
    # w = np.ndarray((30,))
    # Constraints

    ## Represent Portfolios across time

    ### Time step 0
    m.addConstr(
        P_time[0,:] == P_0 + P_buy[0,:] - P_sell[0,:]
    )
    ### Rest of the time
    m.addConstrs((
        P_time[i,:] == P_time[i-1,:] - P_buy[i,:] - P_sell[i,:] for i in range(1,30)
    ))

    ### Final_target
    m.addConstr(
        P_time[29,:] >= P_t
    )

    ## Represent money
    ### First time step
    m.addConstr(
        w[0] == w_0 - prices[0,:] @ P_buy[0,:] + prices[0,:] @ P_sell[0,:] - F @ z_buy[0,:] - F @ z_sell[0,:]
    )
    ## Rest of the time
    m.addConstrs((
        w[i] == w[i-1] - prices[i,:] @ P_buy[i,:] + prices[i,:] @ P_sell[i,:] - F @ z_buy[i,:] - F @ z_sell[i,:] for i in range(1,30)
    ))

    ## Trading fees
    ### if we sell a stock, we pay a trading price
    m.addConstr(
        M*(z_sell) >= P_sell
    )

    ### If we buy a stock, we pay a trading fee
    m.addConstr(
        M*(z_buy) >= P_buy
    )

    # Maximize end Portfolio value
    m.ModelSense = GRB.MAXIMIZE
    m.setObjective(
        # w[29] + prices[29,:] @ P_time[29,:]
        prices[29,:] @ P_time[29,:]
    )
    m.optimize()
    final_portfolio = P_time[29,:].x
    cash = w[29].x 
    final_portfolio_value = cash + prices[29,:] @ final_portfolio
    # print(f"Final Portfolio Value: {final_portfolio_value}")
    # print(f"Free Cash: {free_cash}")
    # print(f"Final Portfolio: {final_portfolio}")
    if print_bool:
        print(f"Init Portf Value: {initial_prices @ P_0}")
        print(f"Final Portfolio Value: {final_portfolio_value}")
        print(f"Cash Init: {w_0[0]}")
        print(f"Cash Final: {cash}")
        print(f"Init Portfolio: {P_0}")
        print(f"Final Portfolio: {final_portfolio}")
        print(f"Target Portfolio: {P_t}")
        print(f"TX Vec Buy: {z_buy.x}")
        print(f"TX Vec Sell: {z_sell.x}")
        print(f"Total Tx Costs: {sum([F @ z_sell.x[i] + F @ z_buy.x[i] for i in range(30)])}")
    return final_portfolio_value, final_portfolio, free_cash

In [9]:
def get_multi_stage_opt_2(P_0, P_t, w_0, initial_budget, stock_price_window, print_bool=False, time_limit=None):   
    # Silence Gurobi output
    env = gp.Env(empty=True)
    env.setParam("OutputFlag",0)
    env.setParam("TimeLimit",time_limit)
    env.start()

    F = 5.95  * np.ones(len(P_0))# trading fees
    # F = 5.95
    # prices = stock_price_window.interpolate().to_numpy()
    prices = stock_price_window.to_numpy()
    M = initial_budget

    buy_list = []
    sell_list = []
    obj_arr = []
    z_b_list = []
    z_s_list = []
    p_val_list = []
    cash_list = []
    p_list = []

    # Define init vars
    P_curr = P_0
    cash_curr = w_0
    # P_time = m.addMVar((30,10), vtype=GRB.INTEGER)

    m = gp.Model(env=env)

    for i, prices in stock_price_window.iterrows():
        prices = prices.to_numpy()
        # m = gp.Model(env=env)

        # Define in loop vars
        # Define Variables
        P_buy = m.addMVar((len(P_0),), vtype=GRB.INTEGER)
        P_sell = m.addMVar((len(P_0),), vtype=GRB.INTEGER)
        z_sell = m.addMVar((len(P_0),), vtype=GRB.BINARY)
        z_buy = m.addMVar((len(P_0),), vtype=GRB.BINARY)

        # print(prices @ P_sell)

        # This is the next iteration of portfolio
        P_next = P_curr + P_buy - P_sell
        cash_next = prices @ P_sell - prices @ P_buy - F @ z_sell - F @ z_buy + cash_curr

        ## Trading fees
        ### if we sell a stock, we pay a trading price
        m.addConstr(
            M*(z_sell) >= P_sell
        )

        ### If we buy a stock, we pay a trading fee
        m.addConstr(
            M*(z_buy) >= P_buy
        )

        # No borrowing
        m.addConstr(cash_next >= 0)

        # No shorting
        m.addConstr(P_next >= 0)

        obj_arr.append(prices @ P_next - F @ z_sell - F @ z_buy)
        cash_curr = cash_next
        P_curr = P_next
        # prob_arr.append(m)

        p_val_list.append(prices @ P_next)
        buy_list.append(P_buy)
        sell_list.append(P_sell)
        z_b_list.append(z_buy)
        z_s_list.append(z_sell)
        cash_list.append(cash_next)
        p_list.append(P_next)


    # Terminal weights constraints
    m.addConstr(P_next >= P_t)

    # Combine all time instances
    obj = sum(obj_arr)
    m.setObjective(obj, GRB.MAXIMIZE)
    m.optimize()
    
    buy_arr = np.array([el.x for el in buy_list])
    sell_arr = np.array([el.x for el in sell_list])
    z_b_arr = np.array([el.x for el in z_b_list])
    z_s_arr = np.array([el.x for el in z_s_list])
    p_val_arr = np.array([el.getValue() for el in p_val_list])
    cash_arr = np.array([el.getValue() for el in cash_list])
    p_arr = np.array([el.getValue() for el in p_list])

    if print_bool:
        print(f"Init Portf Value: {initial_prices @ P_0}")
        print(f"Final Portfolio Value: {prices @ P_next.getValue()}")
        print(f"Cash Init: {w_0}")
        print(f"Cash Final: {cash_next.getValue()}")
        print(f"Init Portfolio: {P_0}")
        print(f"Final Portfolio: {P_next.getValue()}")
        print(f"Target Portfolio: {P_t}")
        print(f"TX Vec Buy: {z_b_arr}")
        print(f"TX Vec Sell: {z_s_arr}")
        print(f"Total Tx Costs: {sum([F @ z_s_arr[i] + F @ z_b_arr[i] for i in range(30)])}")

    return buy_arr, sell_arr, z_s_arr, z_b_arr, p_val_arr, cash_arr, p_arr

In [10]:
# test
rng = np.random.default_rng()
budget = rng.integers(low=1000, high=10000, size=1)
start_dt = np.random.choice(data_pivot.index[:-30], size=1, replace=True)[0]
stock_price_window = get_prices_window(data_clean, start_dt)
P_0, P_t, w_0, initial_prices, final_prices = generate_portfolios(stock_prices = stock_price_window, init_budget=budget)
final_portfolio_value, final_portfolio, free_cash = get_multi_stage_opt(P_0, P_t, w_0, budget, stock_price_window, print_bool=True)
buy_list, sell_list, z_s_list, z_b_list, p_val_arr, cash_arr, p_arr = get_multi_stage_opt_2(P_0, P_t, w_0, budget, stock_price_window, print_bool=True, time_limit=10)

Init Portf Value: 1337.0900149345398
Final Portfolio Value: 1308.8582280397416
Cash Init: 10.909985065460205
Cash Final: 0.7200035572051888
Init Portfolio: [3. 3. 1. 2. 0. 1. 1. 3. 1. 0.]
Final Portfolio: [1. 4. 2. 5. 1. 3. 1. 6. 6. 1.]
Target Portfolio: [1. 4. 2. 4. 1. 3. 1. 2. 3. 1.]
TX Vec Buy: [[ 0.  1.  1.  1.  1.  1.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0. -0. -0.  0.  0.]
 [ 0.  0. -0.  0.  0.  0. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0. -0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0. -0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0.  0.  0.]
 [ 0.  0. -0.  0.  0.  0. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0. -0.  0.]
 [ 0.  0.  0.  0. -0.  0. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0. -0.  0.  0.]
 [-0.  0.  0.

In [11]:
cash_arr

array([[7.80002642e+00],
       [4.86004457e+00],
       [4.86004457e+00],
       [4.99720573e-02],
       [1.90045929e-01],
       [1.90045929e-01],
       [5.81992359e+00],
       [2.64354001e+03],
       [7.44002912e+00],
       [7.44002912e+00],
       [9.45994241e+00],
       [2.91006486e+00],
       [6.69014528e+00],
       [5.37301172e+01],
       [1.37301759e+01],
       [1.64301668e+01],
       [2.57132998e+03],
       [4.04898231e+01],
       [9.69698585e+01],
       [5.02984903e+00],
       [2.97828436e-02],
       [2.44430757e-01],
       [8.34458983e+00],
       [9.46462653e+00],
       [1.70461447e+00],
       [6.82429831e+00],
       [6.80427268e+00],
       [3.62443793e+00],
       [1.18243353e+01],
       [3.74315095e-01]])

In [12]:
pd.DataFrame(data=p_arr, columns = stock_price_window.columns, index=stock_price_window.index)

comnam      WASHINGTON POST CO  DURCO INTERNATIONAL INC  UNIPAC CORP  \
date                                                                   
2020-06-01                 0.0                      0.0          0.0   
2020-06-02                 0.0                      0.0          0.0   
2020-06-03                 0.0                      0.0          0.0   
2020-06-04                 0.0                      0.0          0.0   
2020-06-05                 0.0                      0.0          0.0   
2020-06-08                 0.0                      0.0          0.0   
2020-06-09                 0.0                      0.0          0.0   
2020-06-10                 0.0                      0.0          0.0   
2020-06-11                 0.0                      0.0          0.0   
2020-06-12                 0.0                      0.0          0.0   
2020-06-15                 0.0                    107.0          0.0   
2020-06-16                 0.0                      0.0          0.0   
2020-06-17                 0.0                      0.0          0.0   
2020-06-18                 0.0                      0.0          0.0   
2020-06-19                 0.0                      0.0          0.0   
2020-06-22                 0.0                      0.0          0.0   
2020-06-23                 0.0                      0.0          0.0   
2020-06-24                 0.0                      0.0          0.0   
2020-06-25                12.0                      0.0          0.0   
2020-06-26                 0.0                      0.0          0.0   
2020-06-29                 0.0                      0.0          0.0   
2020-06-30                 0.0                      0.0          0.0   
2020-07-01                 0.0                      0.0          0.0   
2020-07-02                14.0                      0.0          0.0   
2020-07-06                 0.0                      0.0          0.0   
2020-07-07                15.0                      0.0          0.0   
2020-07-08                 0.0                      0.0          0.0   
2020-07-09                16.0                      0.0          0.0   
2020-07-10                 1.0                    185.0          0.0   
2020-07-13                 1.0                    160.0          2.0   

comnam      COMPUGEN LTD  PHILLIPS 66  M G M MIRAGE  \
date                                                  
2020-06-01          84.0          0.0           1.0   
2020-06-02           0.0          0.0          78.0   
2020-06-03           0.0          0.0          78.0   
2020-06-04           0.0          0.0           0.0   
2020-06-05           0.0          0.0           0.0   
2020-06-08           0.0          0.0           0.0   
2020-06-09         155.0          0.0           0.0   
2020-06-10           0.0          0.0           0.0   
2020-06-11         205.0          0.0           0.0   
2020-06-12         205.0          0.0           0.0   
2020-06-15           0.0          0.0           0.0   
2020-06-16         214.0          0.0           0.0   
2020-06-17           2.0         44.0           0.0   
2020-06-18           2.0          0.0           0.0   
2020-06-19         222.0          0.0           0.0   
2020-06-22           0.0          0.0         205.0   
2020-06-23           0.0          0.0           0.0   
2020-06-24           0.0          0.0           0.0   
2020-06-25           0.0          0.0           0.0   
2020-06-26           0.0          0.0         255.0   
2020-06-29         305.0          0.0           0.0   
2020-06-30           0.0          0.0         193.0   
2020-07-01         309.0          0.0           0.0   
2020-07-02           2.0          0.0           0.0   
2020-07-06         318.0          0.0           0.0   
2020-07-07           2.0          0.0           0.0   
2020-07-08         326.0          0.0           0.0   
2020-07-09           0.0          0.0           0.0   
2020-07-10           0.0          0.0        

In [13]:
stock_price_window

comnam      WASHINGTON POST CO  DURCO INTERNATIONAL INC  UNIPAC CORP  \
date                                                                   
2020-06-01          358.600006                27.040001    72.589996   
2020-06-02          360.170013                27.160000    72.080002   
2020-06-03          370.869995                29.090000    72.510002   
2020-06-04          374.279999                29.610001    70.919998   
2020-06-05          386.730011                31.590000    72.230003   
2020-06-08          407.570007                33.630001    70.400002   
2020-06-09          389.799988                31.840000    70.430000   
2020-06-10          372.920013                30.129999    70.440002   
2020-06-11          345.299988                27.000000    67.800003   
2020-06-12          347.839996                28.000000    68.300003   
2020-06-15          350.429993                28.340000    68.800003   
2020-06-16          348.940002                29.690001    69.500000   
2020-06-17          340.019989                28.309999    69.540001   
2020-06-18          334.119995                27.870001    69.709999   
2020-06-19          325.850006                27.719999    70.080002   
2020-06-22          326.059998                27.660000    70.269997   
2020-06-23          325.859985                28.040001    70.180000   
2020-06-24          322.790009                25.799999    68.070000   
2020-06-25          322.660004                27.219999    69.059998   
2020-06-26          327.380005                27.010000    67.900002   
2020-06-29          346.489990                28.230000    69.110001   
2020-06-30          342.670013                28.520000    69.320000   
2020-07-01          336.970001                27.629999    69.029999   
2020-07-02          336.769989                28.340000    69.260002   
2020-07-06          349.250000                29.080000    71.309998   
2020-07-07          332.140015                28.100000    71.699997   
2020-07-08          344.880005                27.570000    71.760002   
2020-07-09          331.160004                27.299999    71.050003   
2020-07-10          344.329987                27.809999    71.650002   
2020-07-13          340.570007                28.320000    70.550003   

comnam      COMPUGEN LTD  PHILLIPS 66  M G M MIRAGE  \
date                                                  
2020-06-01     15.320000    78.830002     17.799999   
2020-06-02     16.790001    81.570000     18.200001   
2020-06-03     17.120001    83.730003     20.260000   
2020-06-04     14.720000    83.129997     21.719999   
2020-06-05     13.610000    87.400002     21.719999   
2020-06-08     13.580000    89.730003     23.760000   
2020-06-09     13.270000    85.669998     22.059999   
2020-06-10     14.020000    84.330002     20.510000   
2020-06-11     12.830000    75.000000     17.840000   
2020-06-12     13.910000    77.260002     19.170000   
2020-06-15     14.860000    75.599998     19.450001   
2020-06-16     14.820000    77.040001     19.350000   
2020-06-17     15.200000    72.879997     18.969999   
2020-06-18     15.420000    76.239998     18.580000   
2020-06-19     15.530000    74.699997     18.209999   
2020-06-22     16.475000    74.400002     17.770000   
2020-06-23     16.209999    74.699997     18.459999   
2020-06-24     14.880000    69.989998     16.930000   
2020-06-25     15.030000    70.070000     16.700001   
2020-06-26     14.590000    68.070000     15.720000   
2020-06-29     14.040000    68.660004     16.820000   
2020-06-30     15.020000    71.900002     16.799999   
2020-07-01     14.740000    69.110001     16.770000   
2020-07-02     15.400000    68.419998     16.860001   
2020-07-06     15.460000    68.089996     16.709999   
2020-07-07     15.820000    64.610001     16.139999   
2020-07-08     15.930000    63.980000     16.299999   
2020-07-09     16.280001    58.980000     16.000000   
2020-07-10     15.860000    61.060001     16.

In [15]:
simulations = 50
rng = np.random.default_rng()
budget_vec = rng.integers(low=1000, high=10000, size=simulations)
start_dt_vec = np.random.choice(data_pivot.index[:-30], size=simulations, replace=True)
col_names = ["portf_val", "cash", "init_budget"]
# df_naive = pd.DataFrame(columns = )
# df_multi = pd.DataFrame(columns = ["portf_val", "final_portf", "cash"])
naive_list = list()
multi_list = list()
multi_list2 = list()
p_list = list()
stock_price_window_list = list()
z_s = list()
z_b = list()
sell = list()
buy = list()
cash = list()

# Could parallelize this but fuck it
for i, budget in enumerate(tqdm(budget_vec)):
    try:
        stock_price_window = get_prices_window(data_clean, start_dt_vec[i])
        P_0, P_t, w_0, initial_prices, final_prices = generate_portfolios(stock_prices = stock_price_window, init_budget=budget)
        final_portfolio_value, final_portfolio, free_cash = get_naive_opt(P_0, P_t, w_0, budget, initial_prices, final_prices, print_bool=False)
        naive_list.append(pd.Series([final_portfolio_value, free_cash, budget], index = col_names))
        # final_portfolio_value, final_portfolio, free_cash = get_multi_stage_opt(P_0, P_t, w_0, budget, stock_price_window)
        # multi_list.append(pd.Series([final_portfolio_value, free_cash, budget], index = col_names))
        buy_list, sell_list, z_s_list, z_b_list, p_val_arr, cash_arr, p_arr = get_multi_stage_opt_2(P_0, P_t, w_0, budget, stock_price_window, print_bool=False, time_limit=5)
        multi_list2.append(pd.Series([p_val_arr[-1], cash_arr[-1], budget], index = col_names))
        p_list.append(p_arr)
        stock_price_window_list.append(stock_price_window)
        z_s.append(z_s_list)
        z_b.append(z_b_list)
        buy.append(buy_list)
        sell.append(sell_list)
        cash.append(cash)
        
    except Exception as e:
        print(e)
        pass
        # print(e)

df_naive = pd.concat(naive_list, axis=1).T
df_multi2 = pd.concat(multi_list2, axis=1).T

 52%|█████▏    | 26/50 [02:36<02:17,  5.73s/it]

Unable to retrieve attribute 'x'


100%|██████████| 50/50 [04:49<00:00,  5.79s/it]


In [47]:
df_naive

portf_val                cash init_budget
0     10462.679108   67.91002082824707        9522
1    244047.346774   68.60804696381115        6094
2      5205.799971  48.199997901916504        4780
3      5409.629978   71.68997204303741        5438
4      2180.779752  59.329758167266846        2093
5      1660.910055  30.690009117126465        1601
6      3469.203988   43.60197892189035        3132
7      1913.750016    53.7000150680542        1888
8      7811.759979   54.02995300292969        7390
9     10748.876042  59.460044145584106        9914
10     1654.350018   69.48000836372375        1592
11     1922.829988  58.919986724853516        1939
12     5591.490105   62.34998798370361        5282
13     7560.981046   57.43337351481114        7561
14     1541.380013    36.3900089263916        1320
15     2198.179958   54.77998161315918        2268
16    11784.665586  60.015676856040955        6261
17     7191.190062  60.100046157836914        4801
18    10690.210005   54.61009073257446        6038
19     2939.690333    66.0358842947544        2478
20     2286.520032   66.80001020431519        2130
21     4461.709938   67.75998306274414        4224
22     7600.139902  52.000003814697266        7376
23     2302.750025   80.44000244140625        2301
24     9011.190114   60.66015291213989        8956
25    10162.863779   61.65981388092041        9104
26     4417.629968  57.854981422424316        3895
27      2999.86007  51.840012550354004        2693
28    10504.646646  62.354141616822744        7949
29     1550.779984   57.38997459411621        1489
30     7926.719958  54.499916553497314        5395
31     9336.170094  62.620113372802734        8384
32     2472.045616   60.59004096984853        2336
33     3920.099948  53.829941749572754        3666
34  1221829.258213   62.02364730834961        5309
35     5263.089958   74.99000549316406        4930
36     6838.960114   67.06001091003418        6436
37     2525.268733  60.087512493133545        2253
38     5072.420086   53.92005252838135        5331
39     2242.242467   65.85998153686523        2072
40     5440.701037   64.23992252349854        6099
41     3001.299885   42.09992694854736        2887
42    10181.890208  41.880165100097656        9173
43     4085.445034   60.87999153137207        3986

In [48]:
df_multi

portf_val                cash init_budget
0     10409.279095   67.91002082824707        9522
1    243994.126774   68.60804696381115        6094
2      5158.199971  48.199997901916504        4780
3      5354.429978   71.68997204303741        5438
4      2132.359751  59.329758167266846        2093
5      1631.160055  30.690009117126465        1601
6      3427.553988   43.60197892189035        3132
7      1862.050022    53.7000150680542        1888
8      7758.209975   54.02995300292969        7390
9     10694.556042  59.460044145584106        9914
10     1618.370017   69.48000836372375        1592
11     1869.649988  58.919986724853516        1939
12     5532.900106   62.34998798370361        5282
13     7507.431046   57.43337351481114        7561
14     1505.680013    36.3900089263916        1320
15     2152.479956   54.77998161315918        2268
16    11725.165586  60.015676856040955        6261
17     7131.690061  60.100046157836914        4801
18    10636.659999   54.61009073257446        6038
19     2886.770331    66.0358842947544        2478
20     2231.410032   66.80001020431519        2130
21     4404.579932   67.75998306274414        4224
22     7550.069903  52.000003814697266        7376
23     2254.290024   80.44000244140625        2301
24     8954.540114   60.66015291213989        8956
25    10103.823758   61.65981388092041        9104
26     4366.369971  57.854981422424316        3895
27      2958.21007  51.840012550354004        2693
28    10445.146646  62.354141616822744        7949
29     1513.089982   57.38997459411621        1489
30     7873.169958  54.499916553497314        5395
31     9285.850093  62.620113372802734        8384
32     2422.364515   60.59004096984853        2336
33     3873.489941  53.829941749572754        3666
34  1221769.758213   62.02364730834961        5309
35     5200.249958   74.99000549316406        4930
36     6778.510115   67.06001091003418        6436
37      2471.79874  60.087512493133545        2253
38     5018.870085   53.92005252838135        5331
39     2181.917467   65.85998153686523        2072
40     5381.201032   64.23992252349854        6099
41     2973.939886   42.09992694854736        2887
42    10140.240208  41.880165100097656        9173
43     4032.715037   60.87999153137207        3986

In [49]:
df_multi2

portf_val      cash  init_budget
0   8.009909e+06  4.898911       9522.0
1   8.843959e+05  0.181526       6094.0
2   2.720100e+04  0.820062       4780.0
3   7.350190e+03  0.985028       5438.0
4   4.068054e+05  2.195234       2093.0
5   3.443370e+03  0.569928       1601.0
6   7.373512e+03  1.511317       3132.0
7   4.259980e+03  0.289864       1888.0
8   1.235017e+04  0.281817       7390.0
9   2.373592e+04  0.438369       9914.0
10  4.912370e+03  1.369999       1592.0
11  4.165580e+03  7.260002       1939.0
12  9.882770e+03  0.068889       5282.0
13  2.569102e+07  0.731977       7561.0
14  4.294930e+03  0.431302       1320.0
15  8.540600e+03  0.372116       2268.0
16  1.105068e+05  0.443504       6261.0
17  5.132705e+04  1.061199       4801.0
18  6.314425e+04  0.152497       6038.0
19  8.694345e+03  0.039367       2478.0
20  6.398380e+03  0.129198       2130.0
21  1.542593e+04  2.738775       4224.0
22  1.597739e+04  4.799842       7376.0
23  3.743580e+03  3.619920       2301.0
24  4.308965e+04  0.566249       8956.0
25  3.212547e+07  6.131534       9104.0
26  1.159779e+04  0.356075       3895.0
27  3.432970e+03  1.070306       2693.0
28  1.707533e+06  4.220753       7949.0
29  3.127940e+03  0.339781       1489.0
30  5.894986e+04  0.009083       5395.0
31  1.246305e+04  0.099396       8384.0
32  9.990549e+03  0.199838       2336.0
33  1.083126e+04  0.345376       3666.0
34  3.061724e+07  8.394945       5309.0
35  1.313783e+04  0.140705       4930.0
36  1.237913e+04  0.019669       6436.0
37  7.863151e+03  0.231898       2253.0
38  2.270787e+04  0.007002       5331.0
39  3.955570e+03  0.262477       2072.0
40  8.081941e+03  0.221201       6099.0
41  6.867150e+03  0.129679       2887.0
42  3.419589e+04  0.456863       9173.0
43  7.092785e+03  0.484827       3986.0

In [52]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        y = df_multi.portf_val,
        x = df_multi.init_budget,
        mode = "markers",
        name = "Old Formulation",
    )
)
fig.add_trace(
    go.Scatter(
        y = df_multi2.portf_val,
        x = df_multi2.init_budget,
        mode = "markers",
        name = "New Formulation",
    )
)
fig.add_trace(
    go.Scatter(
        y = df_naive.portf_val,
        x = df_naive.init_budget,
        mode = "markers",
        name = "Naive",
    )
)

fig.update_xaxes(
    title="Starting Budget"
)

fig.update_yaxes(
    title="Multi-period Advantage",
    type="log"
)

In [58]:
pd.DataFrame(data=p_list[25], columns = stock_price_window_list[25].columns, index=stock_price_window_list[25].index)

comnam      CHEVRON CORP NEW  S L M CORP  COCA COLA EUROPEAN PARTNERS PLC  \
date                                                                        
2021-12-08               0.0         1.0                              1.0   
2021-12-09               0.0         1.0                              1.0   
2021-12-10               0.0         1.0                              1.0   
2021-12-13               0.0      9105.0                              1.0   
2021-12-14               0.0     18209.0                            456.0   
2021-12-15            9104.0     27313.0                           9558.0   
2021-12-16               1.0     36417.0                          18662.0   
2021-12-17            9104.0     45521.0                          27766.0   
2021-12-20               0.0     54625.0                          36870.0   
2021-12-21            9104.0     63729.0                          45974.0   
2021-12-22               0.0     72833.0                          55078.0   
2021-12-23            9104.0     63730.0                          45974.0   
2021-12-27            5667.0     72833.0                          36870.0   
2021-12-28           14771.0     63730.0                          27766.0   
2021-12-29           23875.0     54627.0                          18662.0   
2021-12-30           32979.0     45523.0                           9558.0   
2021-12-31           42083.0     36419.0                            455.0   
2022-01-03           51187.0     27315.0                           6199.0   
2022-01-04           60291.0     18211.0                          15303.0   
2022-01-05           69395.0     27315.0                           6199.0   
2022-01-06           78499.0     18212.0                           9105.0   
2022-01-07           84930.0      9109.0                              1.0   
2022-01-10           94034.0         5.0                           9105.0   
2022-01-11           92618.0      9108.0                          18209.0   
2022-01-12          101722.0     18212.0                          27313.0   
2022-01-13          110826.0      9108.0                          18209.0   
2022-01-14          119930.0         4.0                           9105.0   
2022-01-18          129034.0         4.0                          18209.0   
2022-01-19          138138.0         4.0                          27313.0   
2022-01-20          138138.0        12.0                          27313.0   

comnam      LOMAK PETROLEUM INC  DISCOVER FINANCIAL SERVICES  \
date                                                           
2021-12-08                  0.0                         21.0   
2021-12-09                  0.0                         21.0   
2021-12-10                  0.0                         21.0   
2021-12-13                  0.0                       9125.0   
2021-12-14               9104.0                         22.0   
2021-12-15               9104.0                       6391.0   
2021-12-16              18208.0                          0.0   
2021-12-17              27312.0                          0.0   
2021-12-20              36416.0                       9104.0   
2021-12-21              27312.0                          0.0   
2021-12-22              18208.0                          0.0   
2021-12-23              27312.0                       4186.0   
2021-12-27              18209.0                      13289.0   
2021-12-28               9106.0                      22393.0   
2021-12-29                  3.0                      31497.0   
2021-12-30               9107.0                      40601.0   
2021-12-31              18211.0                      49705.0   
2022-01-03              27311.0                      58809.0   
2022-01-04              36413.0                      58076.0   
2022-01-05              45517.0                      67180.0   
2022-01-06              54621.0                      66061.0   
2022-01-07              63725.0                      56957.0   

In [23]:
prices

comnam      GRUPO SIMEC S A B DE C V  TRAVELERS GROUP INC  \
date                                                        
2020-03-11                    8.6500            50.790001   
2020-03-12                    7.1355            43.259998   
2020-03-13                    7.4500            51.040001   
2020-03-16                    7.7900            41.189999   
2020-03-17                   -6.5000            40.250000   
2020-03-18                    7.0100            36.430000   
2020-03-19                   -7.3800            39.639999   
2020-03-20                    6.9394            38.060001   
2020-03-23                    7.1600            35.389999   
2020-03-24                    7.3300            40.660000   
2020-03-25                    7.2000            41.860001   
2020-03-26                   -7.2450            46.020000   
2020-03-27                    7.2100            43.799999   
2020-03-30                    7.6900            44.080002   
2020-03-31                    7.0900            42.119999   
2020-04-01                    6.7900            38.509998   
2020-04-02                    6.6200            39.230000   
2020-04-03                    6.2500            37.490002   
2020-04-06                    6.3650            41.119999   
2020-04-07                    7.1000            41.250000   
2020-04-08                    7.5465            44.259998   
2020-04-09                    7.3910            47.410000   
2020-04-13                    6.4219            46.680000   
2020-04-14                    6.4823            45.419998   
2020-04-15                    6.2373            42.860001   
2020-04-16                   -6.3750            40.520000   
2020-04-17                   -6.7200            45.450001   
2020-04-20                   -6.2600            44.009998   
2020-04-21                   -6.3300            41.570000   
2020-04-22                   -6.4700            42.240002   

comnam      MOLSON COORS BREWING CO  TRIMBLE NAVIGATION LTD  \
date                                                          
2020-03-11                -6.737501               33.230000   
2020-03-12                40.200001               27.049999   
2020-03-13                43.280001               28.350000   
2020-03-16                45.245100               24.219999   
2020-03-17                -2.607500               22.090000   
2020-03-18                -3.052500               21.320000   
2020-03-19                -3.245001               25.330000   
2020-03-20                -4.222500               26.000000   
2020-03-23                -7.997499               26.540001   
2020-03-24                -5.152500               28.520000   
2020-03-25                40.823551               28.790001   
2020-03-26                -2.747501               30.639999   
2020-03-27                -3.025000               29.850000   
2020-03-30                -1.907501               31.030001   
2020-03-31                -2.425001               31.830000   
2020-04-01                -3.877501               29.100000   
2020-04-02                -2.757500               29.889999   
2020-04-03                -4.447500               28.459999   
2020-04-06                49.125000               31.139999   
2020-04-07                51.150000               32.009998   
2020-04-08                54.305000               33.240002   
2020-04-09                -7.269999               34.459999   
2020-04-13                50.309999               32.189999   
2020-04-14                -5.309999               32.570000   
2020-04-15                -5.502501               32.189999   
2020-04-16                -5.922501               31.340000   
2020-04-17                -4.465000               32.459999   
2020-04-20                -4.714998               32.320000   
2020-04-21                -6.550001               31.680000   
2020-04-22                52.814999               32.180000   

comnam      FIRST COMMONWEALTH

In [19]:
df

comnam      GRUPO SIMEC S A B DE C V  TRAVELERS GROUP INC  \
date                                                        
2020-03-11                       3.0                  0.0   
2020-03-12                       0.0               1552.0   
2020-03-13                       0.0                  0.0   
2020-03-16                       0.0                  0.0   
2020-03-17                    1552.0                  0.0   
2020-03-18                       0.0               1552.0   
2020-03-19                    1552.0                  0.0   
2020-03-20                    1552.0                  0.0   
2020-03-23                       0.0               1552.0   
2020-03-24                       0.0                  2.0   
2020-03-25                       0.0               1552.0   
2020-03-26                    1552.0                  0.0   
2020-03-27                    1552.0                  0.0   
2020-03-30                       1.0                  0.0   
2020-03-31                       1.0                  0.0   
2020-04-01                       1.0                  0.0   
2020-04-02                       1.0               1552.0   
2020-04-03                    1553.0               3104.0   
2020-04-06                    3104.0               4656.0   
2020-04-07                    1552.0               6208.0   
2020-04-08                       0.0               4657.0   
2020-04-09                       0.0               3105.0   
2020-04-13                       0.0               1553.0   
2020-04-14                    1552.0                  1.0   
2020-04-15                       0.0                  1.0   
2020-04-16                       0.0               1553.0   
2020-04-17                    1548.0                  1.0   
2020-04-20                      23.0                  1.0   
2020-04-21                      23.0               1553.0   
2020-04-22                      23.0               1553.0   

comnam      MOLSON COORS BREWING CO  TRIMBLE NAVIGATION LTD  \
date                                                          
2020-03-11                   1553.0                     0.0   
2020-03-12                      1.0                     0.0   
2020-03-13                   1516.0                     0.0   
2020-03-16                      0.0                     0.0   
2020-03-17                   1552.0                  1552.0   
2020-03-18                   3104.0                  3104.0   
2020-03-19                   4656.0                  3206.0   
2020-03-20                   6208.0                  1654.0   
2020-03-23                   7760.0                   102.0   
2020-03-24                   9312.0                     1.0   
2020-03-25                   7760.0                  1552.0   
2020-03-26                   9312.0                     0.0   
2020-03-27                  10864.0                     0.0   
2020-03-30                  12416.0                  1552.0   
2020-03-31                  13968.0                     0.0   
2020-04-01                  15520.0                  1552.0   
2020-04-02                  17072.0                     1.0   
2020-04-03                  18624.0                  1553.0   
2020-04-06                  17072.0                  3104.0   
2020-04-07                  15520.0                  1552.0   
2020-04-08                  13968.0                     0.0   
2020-04-09                  15520.0                     0.0   
2020-04-13                  13968.0                  1551.0   
2020-04-14                  15520.0                  3103.0   
2020-04-15                  17072.0                  1551.0   
2020-04-16                  18624.0                  3103.0   
2020-04-17                  20176.0                  4648.0   
2020-04-20                  21728.0                  3098.0   
2020-04-21                  23280.0                  4642.0   
2020-04-22                  23280.0                  4642.0   

comnam      FIRST COMMONWEALTH

In [22]:
portf_num = 25

fig = go.Figure()

df = pd.DataFrame(data=p_list[portf_num], columns = stock_price_window_list[portf_num].columns, index=stock_price_window_list[portf_num].index)
df_tx_b = pd.DataFrame(data=buy[portf_num], columns = stock_price_window_list[portf_num].columns, index=stock_price_window_list[portf_num].index)
df_tx_s = pd.DataFrame(data=sell[portf_num], columns = stock_price_window_list[portf_num].columns, index=stock_price_window_list[portf_num].index)
prices = stock_price_window_list[portf_num]

fig.add_trace(
    go.Scatter(
        x = df.index,
        y = df.mul(prices).sum(axis=1),
        name="Portfolio Value"
    )
)

In [26]:
fig = go.Figure()

for stock in df_tx_b.columns:
    fig.add_trace(
        go.Scatter(
            x = df_tx_b[stock].index,
            y = df_tx_b[stock].mul(prices[stock]),
            line=dict(width=1, dash='dot'),
            name=stock
        )
    )

    fig.add_trace(
        go.Scatter(
            x = df_tx_s[stock].index,
            y = -df_tx_s[stock].mul(prices[stock]),
            line=dict(width=1, dash='solid'),
            name=stock,
        )
    )

fig